import { ArtProduct, BeautyProduct } from '../types/product';

// Helper to create a Firestore-like timestamp for mock data
const mockTimestamp = () => ({
    toMillis: () => Date.now(),
    seconds: Math.floor(Date.now() / 1000),
    nanoseconds: 0,
    toDate: () => new Date(),
    isEqual: () => true
} as any);

/**
 * Mock Art Dealer Products
 * 10 High-quality mock items for Art Dealer storefronts
 */
export const mockArtProducts: ArtProduct[] = [
    {
        id: 'art-1',
        storeId: 'mock-art-store',
        name: 'Crimson Horizon',
        description: 'A breathtaking abstract oil painting exploring the concept of time and memory through vibrant textures.',
        price: 125000,
        originalPrice: 150000,
        images: ['https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Oil',
            surface: 'Canvas',
            dimensions: '100 x 120 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Abstract',
            style: 'Contemporary'
        }
    },
    {
        id: 'art-2',
        storeId: 'mock-art-store',
        name: 'The Thinker (Modern)',
        description: 'A minimalist bronze sculpture representing the complexity of human thought in the digital age.',
        price: 280000,
        originalPrice: 320000,
        images: ['https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'sculptures',
        available: true,
        artDetails: {
            medium: 'Sculpture',
            surface: 'Bronze',
            dimensions: '45 x 30 x 25 cm',
            year: '2023',
            edition: 'limited-edition',
            isSigned: true,
            isFramed: false,
            hasCertificate: true,
            style: 'Minimalism'
        }
    },
    {
        id: 'art-3',
        storeId: 'mock-art-store',
        name: 'Neon Metropolis',
        description: 'Digital art landscape of a futuristic cityscape, blending cyberpunk aesthetics with traditional Japanese architecture.',
        price: 45000,
        originalPrice: 60000,
        images: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'digital',
        available: true,
        artDetails: {
            medium: 'Digital Art',
            surface: 'Digital File',
            dimensions: '8000 x 6000 px',
            year: '2024',
            edition: 'open-edition',
            isSigned: false,
            hasCertificate: false,
            subject: 'Landscape',
            style: 'Modern'
        }
    },
    {
        id: 'art-4',
        storeId: 'mock-art-store',
        name: 'Serenity in Charcoal',
        description: 'A detailed charcoal portrait of an elder, capturing every wrinkle as a story of a lifetime.',
        price: 75000,
        originalPrice: 95000,
        images: ['https://images.unsplash.com/photo-1544465544-1b71aee9dfa3?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Charcoal',
            surface: 'Paper',
            dimensions: '50 x 70 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Portrait',
            style: 'Realism'
        }
    },
    {
        id: 'art-5',
        storeId: 'mock-art-store',
        name: 'The Blue Void',
        description: 'A minimalist abstract exploration of deep blue hues on a large scale canvas.',
        price: 180000,
        originalPrice: 200000,
        images: ['https://images.unsplash.com/photo-1500462859233-ca6c21419736?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Acrylic',
            surface: 'Canvas',
            dimensions: '150 x 150 cm',
            year: '2023',
            edition: 'original',
            isSigned: true,
            isFramed: false,
            hasCertificate: true,
            style: 'Minimalism'
        }
    },
    {
        id: 'art-6',
        storeId: 'mock-art-store',
        name: 'Floral Explosion',
        description: 'A contemporary mix of traditional floral subjects with urban graffiti elements.',
        price: 110000,
        originalPrice: 135000,
        images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Mixed Media',
            surface: 'Masonite',
            dimensions: '90 x 90 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Still Life',
            style: 'Contemporary'
        }
    },
    {
        id: 'art-7',
        storeId: 'mock-art-store',
        name: 'Autumn Harvest',
        description: 'Classic realism still life painting of harvested fruits on a rustic wooden table.',
        price: 90000,
        originalPrice: 110000,
        images: ['https://images.unsplash.com/photo-1576448191517-4659e93bf3a7?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Oil',
            surface: 'Canvas',
            dimensions: '60 x 80 cm',
            year: '2023',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Still Life',
            style: 'Realism'
        }
    },
    {
        id: 'art-8',
        storeId: 'mock-art-store',
        name: 'Dreamscape #9',
        description: 'A surrealist exploration of subconscious imagery, blending natural forms with geometric shapes.',
        price: 210000,
        originalPrice: 245000,
        images: ['https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Acrylic',
            surface: 'Canvas',
            dimensions: '120 x 150 cm',
            year: '2024',
            edition: 'limited-edition',
            isSigned: true,
            isFramed: false,
            hasCertificate: true,
            style: 'Surrealism'
        }
    },
    {
        id: 'art-9',
        storeId: 'mock-art-store',
        name: 'The Red Dancer',
        description: 'An expressionist piece capturing the movement and emotion of a dancer in a vibrant red robe.',
        price: 155000,
        originalPrice: 180000,
        images: ['https://images.unsplash.com/photo-1577083552431-6e5fd019030b?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Oil',
            surface: 'Paper',
            dimensions: '75 x 100 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Portrait',
            style: 'Impressionism'
        }
    },
    {
        id: 'art-10',
        storeId: 'mock-art-store',
        name: 'Urban Energy',
        description: 'A pop art inspired piece celebrating the chaotic energy of city life with bold colors.',
        price: 65000,
        originalPrice: 85000,
        images: ['https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'digital',
        available: true,
        artDetails: {
            medium: 'Digital Art',
            surface: 'Canvas Print',
            dimensions: '60 x 60 cm',
            year: '2024',
            edition: 'open-edition',
            isSigned: false,
            hasCertificate: false,
            subject: 'Abstract',
            style: 'Modern'
        }
    }
];

/**
 * Mock Beauty Products
 * 10 High-quality mock items for Beauty storefronts
 */
export const mockBeautyProducts: BeautyProduct[] = [
    {
        id: 'beauty-1',
        storeId: 'mock-beauty-store',
        name: 'Glow Serum',
        brand: 'Luminous',
        description: 'Advanced hydrating serum with 10% Hyaluronic Acid for instant glow.',
        price: 15000,
        originalPrice: 22000,
        images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        bottleSizes: [
            { size: '30ml', price: 15000 },
            { size: '50ml', price: 22000, label: 'Value Size' }
        ],
        skinTypes: ['Dry', 'Normal', 'Combination'],
        ingredients: 'Aqua, Sodium Hyaluronate, Panthenol, Glycerin.',
        howToUse: 'Apply 3 drops to clean skin before moisturizing.',
        benefits: 'Plumps skin, reduces fine lines, provides deep hydration.',
        inStock: true
    },
    {
        id: 'beauty-2',
        storeId: 'mock-beauty-store',
        name: 'Matte Liquid Lipstick',
        brand: 'Velvet',
        description: 'Long-wearing, pigment-rich liquid lipstick with a comfortable matte finish.',
        price: 8500,
        originalPrice: 12000,
        images: ['https://images.unsplash.com/photo-1586776108058-a40002e2133a?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'makeup',
        categoryId: 'makeup',
        shades: [
            { name: 'Classic Red', hex: '#BE1E2D', images: ['/lipstick_red.png'] },
            { name: 'Nude Blush', hex: '#E6A8A1', images: ['/lipstick_nude.png'] }
        ],
        benefits: '12-hour wear, smudge-proof, velvet texture.',
        howToUse: 'Apply to clean lips and let dry for 60 seconds.',
        inStock: true
    },
    {
        id: 'beauty-3',
        storeId: 'mock-beauty-store',
        name: 'Midnight Bloom Parfum',
        brand: 'Aura',
        description: 'A sophisticated floral scent with notes of jasmine, patchouli, and vanilla.',
        price: 45000,
        originalPrice: 55000,
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'fragrance',
        categoryId: 'fragrance',
        bottleSizes: [
            { size: '50ml', price: 45000 },
            { size: '100ml', price: 75000 }
        ],
        benefits: 'Long-lasting (8-10 hours), premium essential oils.',
        howToUse: 'Spray on pulse points.',
        inStock: true
    },
    {
        id: 'beauty-4',
        storeId: 'mock-beauty-store',
        name: 'Argan Hair Gold',
        brand: 'SilkPath',
        description: 'Nourishing hair serum to tame frizz and add mirror-like shine.',
        price: 12000,
        originalPrice: 16000,
        images: ['https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'haircare',
        categoryId: 'haircare',
        hairTypes: ['Dry', 'Damaged', 'Curly', 'Frizzy'],
        ingredients: 'Argania Spinosa Kernel Oil, Cyclopentasiloxane.',
        howToUse: 'Apply 2 pumps to damp or dry hair, focusing on ends.',
        benefits: 'Heat protection, frizz control, split end repair.',
        inStock: true
    },
    {
        id: 'beauty-5',
        storeId: 'mock-beauty-store',
        name: 'Sunset Glow Palette',
        brand: 'Chroma',
        description: '12-pan eyeshadow palette featuring warm sunset tones and shimmering metallics.',
        price: 19500,
        originalPrice: 25000,
        images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'makeup',
        categoryId: 'makeup',
        benefits: 'High pigmentation, buttery blendable formula.',
        howToUse: 'Apply mattes as base and shimmers on the center of the lid.',
        inStock: true
    },
    {
        id: 'beauty-6',
        storeId: 'mock-beauty-store',
        name: 'Camellia Cleansing Oil',
        brand: 'PureZen',
        description: 'Gentle oil-to-milk cleanser that removes waterproof makeup without stripping skin.',
        price: 14000,
        originalPrice: 18000,
        images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        skinTypes: ['Sensitive', 'All Skin Types'],
        ingredients: 'Camellia Japonica Seed Oil, Olive Oil, Vitamin E.',
        howToUse: 'Massage on dry face, add water to emulsify, and rinse.',
        benefits: 'Dissolves impurities, softens skin, no oily residue.',
        inStock: true
    },
    {
        id: 'beauty-7',
        storeId: 'mock-beauty-store',
        name: 'Cloud Ceramide Cream',
        brand: 'SkinVeda',
        description: 'Whipped moisturizing cream that repairs the skin barrier and locks in moisture.',
        price: 16500,
        originalPrice: 20000,
        images: ['https://images.unsplash.com/photo-1556228578-019623259cd3?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        skinTypes: ['Dry', 'Sensitive', 'Dehydrated'],
        ingredients: 'Ceramide NP, Squalane, Shea Butter.',
        howToUse: 'Apply as the final step in your routine morning and night.',
        benefits: 'Barrier repair, 24hr hydration, soothing.',
        inStock: true
    },
    {
        id: 'beauty-8',
        storeId: 'mock-beauty-store',
        name: 'Deep Repair Hair Mask',
        brand: 'SilkPath',
        description: 'Intensive weekly treatment for chemically treated or very dry hair.',
        price: 11000,
        originalPrice: 15000,
        images: ['https://images.unsplash.com/photo-1526947425960-945c6e7385a4?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'haircare',
        categoryId: 'haircare',
        hairTypes: ['Damaged', 'Bleached', 'Weak'],
        ingredients: 'Hydrolyzed Keratin, Shea Butter, Biotin.',
        howToUse: 'Apply to damp hair for 10-15 minutes, then rinse thoroughly.',
        benefits: 'Strengthens hair fibers, improves elasticity.',
        inStock: true
    },
    {
        id: 'beauty-9',
        storeId: 'mock-beauty-store',
        name: 'Golden Shimmer Body Oil',
        brand: 'Luminous',
        description: 'A dry body oil that leaves a sun-kissed golden glow and subtle floral scent.',
        price: 13500,
        originalPrice: 17500,
        images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'other',
        categoryId: 'skincare',
        skinTypes: ['All Skin Types'],
        benefits: 'Non-greasy, instant radiance, nourishing.',
        howToUse: 'Shake well and apply to collarbones, arms, and legs.',
        inStock: true
    },
    {
        id: 'beauty-10',
        storeId: 'mock-beauty-store',
        name: 'Dead Sea Mud Mask',
        brand: 'PureZen',
        description: 'Purifying charcoal and mud mask that shrinks pores and detoxifies skin.',
        price: 9000,
        originalPrice: 13000,
        images: ['https://images.unsplash.com/photo-1590156221122-c24efb0a2f59?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        skinTypes: ['Oily', 'Acne-Prone'],
        ingredients: 'Dead Sea Mud, Activated Charcoal, Kaolin Clay.',
        howToUse: 'Apply for 10 minutes until dry, then wash with warm water.',
        benefits: 'Deep pore cleansing, oil control.',
        inStock: true
    }
];
