import { ArtProduct, BeautyProduct, MediaInfluencerProduct, VehicleProduct, FashionProduct, SolarProduct } from '../types/product';



// Helper to create a Firestore-like timestamp for mock data
const mockTimestamp = () => ({
    toMillis: () => Date.now(),
    seconds: Math.floor(Date.now() / 1000),
    nanoseconds: 0,
    toDate: () => new Date(),
    isEqual: () => true
} as any);

/**
 * Mock Art Dealer Products
 * 10 High-quality mock items for Art Dealer storefronts
 */
export const mockArtProducts: ArtProduct[] = [
    {
        id: 'art-1',
        storeId: 'mock-art-store',
        name: 'Crimson Horizon',
        description: 'A breathtaking abstract oil painting exploring the concept of time and memory through vibrant textures.',
        price: 125000,
        originalPrice: 150000,
        images: ['https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Oil',
            surface: 'Canvas',
            dimensions: '100 x 120 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Abstract',
            style: 'Contemporary'
        }
    },
    {
        id: 'art-2',
        storeId: 'mock-art-store',
        name: 'The Thinker (Modern)',
        description: 'A minimalist bronze sculpture representing the complexity of human thought in the digital age.',
        price: 280000,
        originalPrice: 320000,
        images: ['https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'sculptures',
        available: true,
        artDetails: {
            medium: 'Sculpture',
            surface: 'Bronze',
            dimensions: '45 x 30 x 25 cm',
            year: '2023',
            edition: 'limited-edition',
            isSigned: true,
            isFramed: false,
            hasCertificate: true,
            style: 'Minimalism'
        }
    },
    {
        id: 'art-3',
        storeId: 'mock-art-store',
        name: 'Neon Metropolis',
        description: 'Digital art landscape of a futuristic cityscape, blending cyberpunk aesthetics with traditional Japanese architecture.',
        price: 45000,
        originalPrice: 60000,
        images: ['https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'digital',
        available: true,
        artDetails: {
            medium: 'Digital Art',
            surface: 'Digital File',
            dimensions: '8000 x 6000 px',
            year: '2024',
            edition: 'open-edition',
            isSigned: false,
            hasCertificate: false,
            subject: 'Landscape',
            style: 'Modern'
        }
    },
    {
        id: 'art-4',
        storeId: 'mock-art-store',
        name: 'Serenity in Charcoal',
        description: 'A detailed charcoal portrait of an elder, capturing every wrinkle as a story of a lifetime.',
        price: 75000,
        originalPrice: 95000,
        images: ['https://images.unsplash.com/photo-1544465544-1b71aee9dfa3?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Charcoal',
            surface: 'Paper',
            dimensions: '50 x 70 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Portrait',
            style: 'Realism'
        }
    },
    {
        id: 'art-5',
        storeId: 'mock-art-store',
        name: 'The Blue Void',
        description: 'A minimalist abstract exploration of deep blue hues on a large scale canvas.',
        price: 180000,
        originalPrice: 200000,
        images: ['https://images.unsplash.com/photo-1500462859233-ca6c21419736?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Acrylic',
            surface: 'Canvas',
            dimensions: '150 x 150 cm',
            year: '2023',
            edition: 'original',
            isSigned: true,
            isFramed: false,
            hasCertificate: true,
            style: 'Minimalism'
        }
    },
    {
        id: 'art-6',
        storeId: 'mock-art-store',
        name: 'Floral Explosion',
        description: 'A contemporary mix of traditional floral subjects with urban graffiti elements.',
        price: 110000,
        originalPrice: 135000,
        images: ['https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Mixed Media',
            surface: 'Masonite',
            dimensions: '90 x 90 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Still Life',
            style: 'Contemporary'
        }
    },
    {
        id: 'art-7',
        storeId: 'mock-art-store',
        name: 'Autumn Harvest',
        description: 'Classic realism still life painting of harvested fruits on a rustic wooden table.',
        price: 90000,
        originalPrice: 110000,
        images: ['https://images.unsplash.com/photo-1576448191517-4659e93bf3a7?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Oil',
            surface: 'Canvas',
            dimensions: '60 x 80 cm',
            year: '2023',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Still Life',
            style: 'Realism'
        }
    },
    {
        id: 'art-8',
        storeId: 'mock-art-store',
        name: 'Dreamscape #9',
        description: 'A surrealist exploration of subconscious imagery, blending natural forms with geometric shapes.',
        price: 210000,
        originalPrice: 245000,
        images: ['https://images.unsplash.com/photo-1543857778-c4a1a3e0b2eb?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Acrylic',
            surface: 'Canvas',
            dimensions: '120 x 150 cm',
            year: '2024',
            edition: 'limited-edition',
            isSigned: true,
            isFramed: false,
            hasCertificate: true,
            style: 'Surrealism'
        }
    },
    {
        id: 'art-9',
        storeId: 'mock-art-store',
        name: 'The Red Dancer',
        description: 'An expressionist piece capturing the movement and emotion of a dancer in a vibrant red robe.',
        price: 155000,
        originalPrice: 180000,
        images: ['https://images.unsplash.com/photo-1577083552431-6e5fd019030b?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Oil',
            surface: 'Paper',
            dimensions: '75 x 100 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Portrait',
            style: 'Impressionism'
        }
    },
    {
        id: 'art-10',
        storeId: 'mock-art-store',
        name: 'Urban Energy',
        description: 'A pop art inspired piece celebrating the chaotic energy of city life with bold colors.',
        price: 65000,
        originalPrice: 85000,
        images: ['https://images.unsplash.com/photo-1563089145-599997674d42?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'digital',
        available: true,
        artDetails: {
            medium: 'Digital Art',
            surface: 'Canvas Print',
            dimensions: '60 x 60 cm',
            year: '2024',
            edition: 'open-edition',
            isSigned: false,
            hasCertificate: false,
            subject: 'Abstract',
            style: 'Modern'
        }
    },
    {
        id: 'art-11',
        storeId: 'mock-art-store',
        name: 'Monochrome Streets',
        description: 'A striking black and white street photography piece capturing the essence of urban life.',
        price: 35000,
        originalPrice: 45000,
        images: ['https://images.unsplash.com/photo-1542456578-1ca7b824ef78?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'photography',
        available: true,
        artDetails: {
            medium: 'Photography',
            surface: 'Archival Paper',
            dimensions: '40 x 50 cm',
            year: '2023',
            edition: 'limited-edition',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Architecture',
            style: 'Documentary'
        }
    },
    {
        id: 'art-12',
        storeId: 'mock-art-store',
        name: 'Echoes of Time',
        description: 'A mixed media piece incorporating vintage documents, acrylics, and gold leaf.',
        price: 130000,
        originalPrice: 160000,
        images: ['https://images.unsplash.com/photo-1578301978693-85fa9c03fa75?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'mixed-media',
        available: true,
        artDetails: {
            medium: 'Mixed Media',
            surface: 'Wood Panel',
            dimensions: '80 x 100 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: false,
            hasCertificate: true,
            subject: 'Abstract',
            style: 'Contemporary'
        }
    },
    {
        id: 'art-13',
        storeId: 'mock-art-store',
        name: 'Sunset over the Marina',
        description: 'A vibrant impressionist painting capturing the golden hour over a bustling marina.',
        price: 95000,
        originalPrice: 120000,
        images: ['https://images.unsplash.com/photo-1518991444122-eb1fe6be62b7?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'art',
        categoryId: 'paintings',
        available: true,
        artDetails: {
            medium: 'Oil',
            surface: 'Canvas',
            dimensions: '60 x 90 cm',
            year: '2024',
            edition: 'original',
            isSigned: true,
            isFramed: true,
            hasCertificate: true,
            subject: 'Landscape',
            style: 'Impressionism'
        }
    }
];

/**
 * Mock Beauty Products
 * 10 High-quality mock items for Beauty storefronts
 */
export const mockBeautyProducts: BeautyProduct[] = [
    {
        id: 'beauty-1',
        storeId: 'mock-beauty-store',
        name: 'Glow Serum',
        brand: 'Luminous',
        description: 'Advanced hydrating serum with 10% Hyaluronic Acid for instant glow.',
        price: 15000,
        originalPrice: 22000,
        images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        bottleSizes: [
            { size: '30ml', price: 15000 },
            { size: '50ml', price: 22000, label: 'Value Size' }
        ],
        skinTypes: ['Dry', 'Normal', 'Combination'],
        ingredients: 'Aqua, Sodium Hyaluronate, Panthenol, Glycerin.',
        howToUse: 'Apply 3 drops to clean skin before moisturizing.',
        benefits: 'Plumps skin, reduces fine lines, provides deep hydration.',
        inStock: true
    },
    {
        id: 'beauty-2',
        storeId: 'mock-beauty-store',
        name: 'Matte Liquid Lipstick',
        brand: 'Velvet',
        description: 'Long-wearing, pigment-rich liquid lipstick with a comfortable matte finish.',
        price: 8500,
        originalPrice: 12000,
        images: ['https://images.unsplash.com/photo-1586776108058-a40002e2133a?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'makeup',
        categoryId: 'makeup',
        shades: [
            { name: 'Classic Red', hex: '#BE1E2D', images: ['/lipstick_red.png'] },
            { name: 'Nude Blush', hex: '#E6A8A1', images: ['/lipstick_nude.png'] }
        ],
        benefits: '12-hour wear, smudge-proof, velvet texture.',
        howToUse: 'Apply to clean lips and let dry for 60 seconds.',
        inStock: true
    },
    {
        id: 'beauty-3',
        storeId: 'mock-beauty-store',
        name: 'Midnight Bloom Parfum',
        brand: 'Aura',
        description: 'A sophisticated floral scent with notes of jasmine, patchouli, and vanilla.',
        price: 45000,
        originalPrice: 55000,
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'fragrance',
        categoryId: 'fragrance',
        bottleSizes: [
            { size: '50ml', price: 45000 },
            { size: '100ml', price: 75000 }
        ],
        benefits: 'Long-lasting (8-10 hours), premium essential oils.',
        howToUse: 'Spray on pulse points.',
        inStock: true
    },
    {
        id: 'beauty-4',
        storeId: 'mock-beauty-store',
        name: 'Argan Hair Gold',
        brand: 'SilkPath',
        description: 'Nourishing hair serum to tame frizz and add mirror-like shine.',
        price: 12000,
        originalPrice: 16000,
        images: ['https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'haircare',
        categoryId: 'haircare',
        hairTypes: ['Dry', 'Damaged', 'Curly', 'Frizzy'],
        ingredients: 'Argania Spinosa Kernel Oil, Cyclopentasiloxane.',
        howToUse: 'Apply 2 pumps to damp or dry hair, focusing on ends.',
        benefits: 'Heat protection, frizz control, split end repair.',
        inStock: true
    },
    {
        id: 'beauty-5',
        storeId: 'mock-beauty-store',
        name: 'Sunset Glow Palette',
        brand: 'Chroma',
        description: '12-pan eyeshadow palette featuring warm sunset tones and shimmering metallics.',
        price: 19500,
        originalPrice: 25000,
        images: ['https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'makeup',
        categoryId: 'makeup',
        benefits: 'High pigmentation, buttery blendable formula.',
        howToUse: 'Apply mattes as base and shimmers on the center of the lid.',
        inStock: true
    },
    {
        id: 'beauty-6',
        storeId: 'mock-beauty-store',
        name: 'Camellia Cleansing Oil',
        brand: 'PureZen',
        description: 'Gentle oil-to-milk cleanser that removes waterproof makeup without stripping skin.',
        price: 14000,
        originalPrice: 18000,
        images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        skinTypes: ['Sensitive', 'All Skin Types'],
        ingredients: 'Camellia Japonica Seed Oil, Olive Oil, Vitamin E.',
        howToUse: 'Massage on dry face, add water to emulsify, and rinse.',
        benefits: 'Dissolves impurities, softens skin, no oily residue.',
        inStock: true
    },
    {
        id: 'beauty-7',
        storeId: 'mock-beauty-store',
        name: 'Cloud Ceramide Cream',
        brand: 'SkinVeda',
        description: 'Whipped moisturizing cream that repairs the skin barrier and locks in moisture.',
        price: 16500,
        originalPrice: 20000,
        images: ['https://images.unsplash.com/photo-1556228578-019623259cd3?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        skinTypes: ['Dry', 'Sensitive', 'Dehydrated'],
        ingredients: 'Ceramide NP, Squalane, Shea Butter.',
        howToUse: 'Apply as the final step in your routine morning and night.',
        benefits: 'Barrier repair, 24hr hydration, soothing.',
        inStock: true
    },
    {
        id: 'beauty-8',
        storeId: 'mock-beauty-store',
        name: 'Deep Repair Hair Mask',
        brand: 'SilkPath',
        description: 'Intensive weekly treatment for chemically treated or very dry hair.',
        price: 11000,
        originalPrice: 15000,
        images: ['https://images.unsplash.com/photo-1526947425960-945c6e7385a4?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'haircare',
        categoryId: 'haircare',
        hairTypes: ['Damaged', 'Bleached', 'Weak'],
        ingredients: 'Hydrolyzed Keratin, Shea Butter, Biotin.',
        howToUse: 'Apply to damp hair for 10-15 minutes, then rinse thoroughly.',
        benefits: 'Strengthens hair fibers, improves elasticity.',
        inStock: true
    },
    {
        id: 'beauty-9',
        storeId: 'mock-beauty-store',
        name: 'Golden Shimmer Body Oil',
        brand: 'Luminous',
        description: 'A dry body oil that leaves a sun-kissed golden glow and subtle floral scent.',
        price: 13500,
        originalPrice: 17500,
        images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'other',
        categoryId: 'skincare',
        skinTypes: ['All Skin Types'],
        benefits: 'Non-greasy, instant radiance, nourishing.',
        howToUse: 'Shake well and apply to collarbones, arms, and legs.',
        inStock: true
    },
    {
        id: 'beauty-10',
        storeId: 'mock-beauty-store',
        name: 'Dead Sea Mud Mask',
        brand: 'PureZen',
        description: 'Purifying charcoal and mud mask that shrinks pores and detoxifies skin.',
        price: 9000,
        originalPrice: 13000,
        images: ['https://images.unsplash.com/photo-1590156221122-c24efb0a2f59?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'skincare',
        categoryId: 'skincare',
        skinTypes: ['Oily', 'Acne-Prone'],
        ingredients: 'Dead Sea Mud, Activated Charcoal, Kaolin Clay.',
        howToUse: 'Apply for 10 minutes until dry, then wash with warm water.',
        benefits: 'Deep pore cleansing, oil control.',
        inStock: true
    },
    {
        id: 'beauty-11',
        storeId: 'mock-beauty-store',
        name: 'Pro Artistry Brush Set',
        brand: 'LuxeTools',
        description: 'A 12-piece professional grade makeup brush set with vegan bristles and a travel case.',
        price: 25000,
        originalPrice: 32000,
        images: ['https://images.unsplash.com/photo-1596462502278-27bfdd403348?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'other',
        categoryId: 'tools',
        benefits: 'Flawless application, perfectly blended makeup.',
        howToUse: 'Use specific brushes for foundation, powder, blush, and eye makeup.',
        inStock: true
    },
    {
        id: 'beauty-12',
        storeId: 'mock-beauty-store',
        name: 'Marine Collagen Peptides',
        brand: 'GlowInner',
        description: 'Unflavored marine collagen powder for healthy hair, skin, and nails.',
        price: 18000,
        originalPrice: 24000,
        images: ['https://images.unsplash.com/photo-1584305574636-f38b2488a1cd?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'other',
        categoryId: 'wellness',
        ingredients: '100% Hydrolyzed Marine Collagen.',
        howToUse: 'Mix 1 scoop daily into your coffee, smoothie, or water.',
        benefits: 'Promotes skin elasticity, strengthens nails.',
        inStock: true
    },
    {
        id: 'beauty-13',
        storeId: 'mock-beauty-store',
        name: 'Luminous Foundation',
        brand: 'Chroma',
        description: 'A medium-coverage, buildable foundation that leaves a natural, radiant finish.',
        price: 16500,
        originalPrice: 21000,
        images: ['https://images.unsplash.com/photo-1631214500515-e4ace7a44fbc?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'makeup',
        categoryId: 'makeup',
        skinTypes: ['Normal', 'Combination', 'Dry'],
        shades: [
            { name: 'Warm Honey', hex: '#D2A27F', images: [] },
            { name: 'Deep Mocha', hex: '#5A3F33', images: [] }
        ],
        benefits: 'Hydrating, long-lasting, photo-ready.',
    }
];

/**
 * Mock Solar Products
 */
export const mockSolarProducts: SolarProduct[] = [
    {
        id: 'solar-1',
        storeId: 'mock-solar-store',
        name: 'Canadian Solar 550W Mono',
        brand: 'Canadian Solar',
        condition: 'brand-new',
        quantity: 50,
        description: 'High-efficiency monocrystalline solar panel with half-cut cell technology.',
        price: 85000,
        images: ['https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'solar',
        subtype: 'solar-panels',
        wattage: '550W',
        cellType: 'Monocrystalline',
        efficiencyRating: '21.3%',
        warranty: true,
        warrantyDuration: '25 Years',
        available: true
    },
    {
        id: 'solar-2',
        storeId: 'mock-solar-store',
        name: 'Luminous 5kVA Hybrid Inverter',
        brand: 'Luminous',
        condition: 'brand-new',
        quantity: 20,
        description: 'Pure sine wave hybrid inverter with MPPT charge controller built-in.',
        price: 450000,
        images: ['https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'solar',
        subtype: 'inverters',
        powerCapacity: '5kVA',
        inverterType: 'Hybrid',
        systemVoltage: '48V',
        warranty: true,
        warrantyDuration: '2 Years',
        available: true
    },
    {
        id: 'solar-3',
        storeId: 'mock-solar-store',
        name: 'Felicity Solar 10kWh Lithium Battery',
        brand: 'Felicity',
        condition: 'brand-new',
        quantity: 15,
        description: 'Deep cycle LiFePO4 battery for long-lasting energy storage.',
        price: 1200000,
        images: ['https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'solar',
        subtype: 'batteries',
        batteryCapacity: '200Ah / 10kWh',
        batteryChemistry: 'LiFePO4',
        lifeCycles: '6000+',
        warranty: true,
        warrantyDuration: '5 Years',
        available: true
    },
    {
        id: 'solar-4',
        storeId: 'mock-solar-store',
        name: 'EcoFlow Delta 2 Max (2048Wh)',
        brand: 'EcoFlow',
        condition: 'brand-new',
        quantity: 12,
        description: 'Portable power station with LFP battery, 2400W AC output, and fast charging.',
        price: 1850000,
        images: ['https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'solar',
        subtype: 'solar-kits',
        powerCapacity: '2048Wh / 2400W',
        batteryChemistry: 'LFP',
        lifeCycles: '3000+',
        warranty: true,
        warrantyDuration: '5 Years',
        available: true
    },
    {
        id: 'solar-5',
        storeId: 'mock-solar-store',
        name: 'All-in-One Solar Street Light 300W',
        brand: 'Generic Premium',
        condition: 'brand-new',
        quantity: 100,
        description: 'LED street light with integrated solar panel and motion sensor.',
        price: 45000,
        images: ['https://images.unsplash.com/photo-1510563800743-a9230e5460ef?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'solar',
        subtype: 'dc-appliances',
        wattage: '300W',
        warranty: true,
        warrantyDuration: '1 Year',
        available: true
    },
    {
        id: 'solar-6',
        storeId: 'mock-solar-store',
        name: 'Schneider Conext XW Pro 8.5kW',
        brand: 'Schneider',
        condition: 'brand-new',
        quantity: 5,
        description: 'Industrial-grade hybrid inverter for large residential and commercial systems.',
        price: 4200000,
        images: ['https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'solar',
        subtype: 'inverters',
        powerCapacity: '8.5kW',
        inverterType: 'Hybrid',
        systemVoltage: '48V',
        efficiencyRating: '95%',
        warranty: true,
        warrantyDuration: '10 Years',
        available: true
    }
];

/**
 * Mock Candle Products
 */
export const mockCandleProducts: BeautyProduct[] = [
    {
        id: 'candle-1',
        storeId: 'mock-media-store',
        name: 'Midnight Lavender Soy Candle',
        brand: 'Luminous Glow',
        description: 'Soothing lavender scent mixed with subtle vanilla notes. Perfect for relaxation.',
        price: 12000,
        images: ['https://images.unsplash.com/photo-1605651202774-7d573fd3f12d?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'candles',
        categoryId: 'candles',
        category: 'Candles & Home Fragrance',
        scent: 'Lavender & Vanilla',
        burnTime: '45 Hours',
        waxType: '100% Soy Wax',
        bottleSizes: [{ size: '250g', price: 12000 }],
        inStock: true
    },
    {
        id: 'candle-2',
        storeId: 'mock-media-store',
        name: 'Spiced Sandalwood Decor Candle',
        brand: 'Aura Home',
        description: 'A warm, woody aroma in a beautiful ceramic jar that doubles as decor.',
        price: 18500,
        images: ['https://images.unsplash.com/photo-1596433809252-260c2745dfdd?w=800&q=80'],

        views: 0,
        createdAt: mockTimestamp(),
        productType: 'beauty',
        subtype: 'candles',
        categoryId: 'candles',
        category: 'Candles & Home Fragrance',
        scent: 'Sandalwood & Amber',
        burnTime: '60 Hours',
        waxType: 'Beeswax Blend',
        bottleSizes: [{ size: '400g', price: 18500 }],
        inStock: true
    }
];

/**
 * Mock Media Influencer Products
 * A diverse mix of PR services, automobiles, and luxury fashion
 */
export const mockMediaProducts: (MediaInfluencerProduct | VehicleProduct | FashionProduct | BeautyProduct)[] = [
    // --- PR & COLLAB SERVICES ---
    {
        id: 'media-1',
        storeId: 'mock-media-store',
        name: 'Dedicated Instagram Reel',
        description: 'High-quality 60s dedicated reel for your brand. Includes trend research and 1 revision.',
        price: 250000,
        originalPrice: 300000,
        images: ['https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'media-influencer',
        subtype: 'service',
        platform: 'Instagram',
        deliveryTimeDays: 5,
        revisionsAllowed: 1,
        categoryId: 'pr-collabs',
        category: 'PR & Collab Services',
        isActive: true
    },
    {
        id: 'media-2',
        storeId: 'mock-media-store',
        name: 'TikTok Sound Promo (Viral)',
        description: 'I will use your brand sound in a creative lifestyle vlog. High engagement guaranteed.',
        price: 75000,
        images: ['https://images.unsplash.com/photo-1596524430615-b46475ddff6e?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'media-influencer',
        subtype: 'service',
        platform: 'TikTok',
        deliveryTimeDays: 2,
        revisionsAllowed: 0,
        categoryId: 'pr-collabs',
        category: 'PR & Collab Services',
        isActive: true
    },
    {
        id: 'media-3',
        storeId: 'mock-media-store',
        name: 'YouTube Integration (2 Mins)',
        description: 'A dedicated 2-minute integration segment in my next weekly vlog.',
        price: 400000,
        images: ['https://images.unsplash.com/photo-1492724441997-5dc865305da7?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'media-influencer',
        subtype: 'service',
        platform: 'YouTube',
        deliveryTimeDays: 7,
        revisionsAllowed: 2,
        categoryId: 'pr-collabs',
        category: 'PR & Collab Services',
        isActive: true
    },
    {
        id: 'media-4',
        storeId: 'mock-media-store',
        name: '24hr Instagram Story Post',
        description: '3 slides maximum with custom link integration and CTA.',
        price: 45000,
        images: ['https://images.unsplash.com/photo-1611262588024-d12430b98920?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'media-influencer',
        subtype: 'service',
        platform: 'Instagram',
        deliveryTimeDays: 1,
        revisionsAllowed: 0,
        categoryId: 'pr-collabs',
        category: 'PR & Collab Services',
        isActive: true,
        commission: 15
    },
    {
        id: 'media-birthday',
        storeId: 'mock-media-store',
        name: 'Personalized Birthday Shoutout',
        description: 'A special 30s video message wishing you or your loved one a happy birthday!',
        price: 25000,
        images: ['https://images.unsplash.com/photo-1513151233558-d860c5398176?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'media-influencer',
        subtype: 'service',
        platform: 'Cross-Platform',
        deliveryTimeDays: 2,
        revisionsAllowed: 0,
        categoryId: 'pr-collabs',
        category: 'PR & Collab Services',
        isActive: true,
        commission: 15
    },
    {
        id: 'media-event',
        storeId: 'mock-media-store',
        name: 'Event Appearance (2 Hours)',
        description: 'Physical appearance at your brand launch or private event. Includes 5 photos/stories.',
        price: 500000,
        images: ['https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'media-influencer',
        subtype: 'service',
        platform: 'Cross-Platform',
        deliveryTimeDays: 14,
        revisionsAllowed: 0,
        categoryId: 'pr-collabs',
        category: 'PR & Collab Services',
        isActive: true,
        commission: 15
    },
    {
        id: 'media-unboxing',
        storeId: 'mock-media-store',
        name: 'Premium Product Unboxing',
        description: 'A detailed unboxing video showing first impressions and product features.',
        price: 120000,
        images: ['https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'media-influencer',
        subtype: 'service',
        platform: 'Instagram',
        deliveryTimeDays: 4,
        revisionsAllowed: 1,
        categoryId: 'pr-collabs',
        category: 'PR & Collab Services',
        isActive: true,
        commission: 15
    },

    // --- CANDLES & HOME FRAGRANCE ---
    ...mockCandleProducts.map(c => ({ ...c, storeId: 'mock-media-store' })) as any[],

    // --- SKINCARE ---
    ...mockBeautyProducts.filter(p => p.subtype === 'skincare').map(p => ({ ...p, storeId: 'mock-media-store' })) as any[],

    /*
    // --- AUTOMOBILES (Hidden for now) ---
    {
        id: 'media-v1',
        storeId: 'mock-media-store',
        name: 'Mercedes Benz GLC 300 2021',
        description: 'Direct Tokunbo, panoramic roof, ambient lighting, low mileage.',
        price: 45000000,
        images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'vehicle',
        vehicleDetails: {
            make: 'Mercedes-Benz',
            model: 'GLC 300',
            year: 2021,
            condition: 'foreign-used',
            transmission: 'automatic',
            fuelType: 'petrol',
            bodyType: 'suv',
            color: 'Obsidian Black',
            mileage: 34000,
            location: 'Lagos'
        },
        categoryId: 'automobiles',
        category: 'Cars For Sale',
        available: true
    },
    {
        id: 'media-v2',
        storeId: 'mock-media-store',
        name: 'Lexus RX 350 F-Sport 2020',
        description: 'Super clean, custom red leather interior, fully loaded.',
        price: 38000000,
        images: ['https://images.unsplash.com/photo-1520050206274-a1ae446cb3cc?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'vehicle',
        vehicleDetails: {
            make: 'Lexus',
            model: 'RX 350',
            year: 2020,
            condition: 'foreign-used',
            transmission: 'automatic',
            fuelType: 'petrol',
            bodyType: 'suv',
            color: 'White Pearl',
            mileage: 41000,
            location: 'Abuja'
        },
        categoryId: 'automobiles',
        category: 'Cars For Sale',
        available: true
    },
    {
        id: 'media-v3',
        storeId: 'mock-media-store',
        name: 'Toyota Camry XSE 2022',
        description: 'Nigerian used, first body paint, extremely well maintained.',
        price: 21000000,
        images: ['https://images.unsplash.com/photo-1621007947382-bb3c3994e3fd?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'vehicle',
        vehicleDetails: {
            make: 'Toyota',
            model: 'Camry XSE',
            year: 2022,
            condition: 'nigerian-used',
            transmission: 'automatic',
            fuelType: 'petrol',
            bodyType: 'sedan',
            color: 'Silver Metallic',
            mileage: 12000,
            location: 'Lagos'
        },
        categoryId: 'automobiles',
        category: 'Cars For Sale',
        available: true
    },
    */

    // --- APPAREL ---
    {
        id: 'media-f1',
        storeId: 'mock-media-store',
        name: 'Satin Modest Abaya',
        description: 'Flowy, elegant satin finish with intricate sleeve detailing. Includes matching hijab.',
        price: 35000,
        images: ['/images/abaya.png'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'fashion',
        sizeCategory: 'clothing',
        sizes: ['S', 'M', 'L', 'XL'],
        colors: [
            { name: 'Navy Blue', hex: '#000080', images: [] },
            { name: 'Emerald', hex: '#50c878', images: [] }
        ],
        sizeChart: { type: 'jallab-standard' },
        categoryId: 'apparel',
        category: 'Apparel & Modest Wear'
    },
    {
        id: 'media-f2',
        storeId: 'mock-media-store',
        name: 'Casual Two-Piece Lounge Wear',
        description: 'Breathable cotton blend for premium everyday comfort.',
        price: 22000,
        images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'fashion',
        sizeCategory: 'clothing',
        sizes: ['M', 'L'],
        colors: [{ name: 'Beige', hex: '#f5f5dc', images: [] }],
        sizeChart: { type: 'nigerian-standard' },
        categoryId: 'apparel',
        category: 'Apparel & Modest Wear'
    },
    {
        id: 'media-f3',
        storeId: 'mock-media-store',
        name: 'Luxury Sequin Evening Dress',
        description: 'Hand-sewn sequins for a dazzling look at high-profile events.',
        price: 85000,
        images: ['https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'fashion',
        sizeCategory: 'clothing',
        sizes: ['S', 'M', 'L'],
        colors: [{ name: 'Gold', hex: '#ffd700', images: [] }],
        sizeChart: { type: 'nigerian-standard' },
        categoryId: 'apparel',
        category: 'Apparel & Modest Wear'
    },

    // --- FRAGRANCES ---
    {
        id: 'media-p1',
        storeId: 'mock-media-store',
        name: 'Oud Mood Premium Perfume',
        description: 'A rich, woody scent with long-lasting projection. 100ml EDP.',
        price: 15000,
        images: ['https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'fashion',
        sizeCategory: 'clothing',
        sizes: ['100ml', '50ml'],
        colors: [],
        sizeChart: { type: 'oil-perfume-volume' },
        categoryId: 'fragrances',
        category: 'Perfumes & Oils'
    },
    {
        id: 'media-p2',
        storeId: 'mock-media-store',
        name: 'Baccarat Rouge 540 (Decant)',
        description: 'Highly concentrated authentic decant. Versatile and luxurious.',
        price: 45000,
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80'],
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'fashion',
        sizeCategory: 'clothing',
        sizes: ['10ml'],
        colors: [],
        sizeChart: { type: 'oil-perfume-volume' },
        categoryId: 'fragrances',
        category: 'Perfumes & Oils'
    },
    {
        id: 'media-p3',
        storeId: 'mock-media-store',
        name: 'Vanilla Musk Scented Oil',
        description: 'Exquisite vanilla blend in a non-alcoholic oil base.',
        price: 8000,
        originalPrice: 10000,
        images: ['https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&q=80'], // Fixed 404
        views: 0,
        createdAt: mockTimestamp(),
        productType: 'fashion',
        sizeCategory: 'clothing',
        sizes: ['3ml', '6ml', '12ml'],
        colors: [],
        sizeChart: { type: 'oil-perfume-volume' },
        categoryId: 'fragrances',
        category: 'Perfumes & Oils'
    }
];
